# Descriptive Analysis
I will try to analyse that how the individual feature affect the churned customer.\
and also I will try to know that which one affects more.\
and Finally, Which classes of categorical feature may affect the results

In [2]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://vivek:password123@localhost/churn_db"
)

In [7]:
import pymysql
import pandas as pd
conn = pymysql.connect(
    host="localhost",
    user="vivek",
    password="password123",
    database="churn_db"
)

In [19]:
query = """
SELECT * FROM churn LIMIT 10;
"""
df = pd.read_sql(query,engine)
df

,CustomerID,Age,Gender,Tenure,Usage_Frequency,Support_Calls,Payment_Delay,Subscription_Type,Contract_Length,Total_Spend,Last_Interaction,Churn
0,1,22,Female,25,14,4,27,Basic,Monthly,598.0,9,1.0
1,2,30,Female,39,14,5,18,Standard,Annual,932.0,17,1.0
2,2,41,Female,28,28,7,13,Standard,Monthly,584.0,20,0.0
3,3,47,Male,27,10,2,29,Premium,Annual,757.0,21,0.0
4,3,65,Female,49,1,10,8,Basic,Monthly,557.0,6,1.0
5,4,55,Female,14,4,6,18,Basic,Quarterly,185.0,3,1.0
6,4,35,Male,9,12,5,17,Premium,Quarterly,232.0,18,0.0
7,5,53,Female,58,24,9,2,Standard,Annual,533.0,18,0.0
8,5,58,Male,38,21,7,7,Standard,Monthly,396.0,29,1.0
9,6,23,Male,32,20,5,8,Basic,Monthly,617.0,20,1.0

In [24]:
query = """
SELECT Churn,COUNT(Churn) as total_customer FROM churn
GROUP BY Churn ;
"""
df = pd.read_sql(query,engine)
df

  Churn  total_customer
0   0.0          224714
1   1.0          280492

Nearly 44.4% customers have left the company that meeans there exist the problem.

In [26]:
query = """
SELECT AVG(Age) as avg_age,AVG(Tenure) as avg_Ten,AVG(Usage_Frequency) as avg_Fre,AVG(Support_Calls) as avg_SC,AVG(Payment_Delay) as avg_PD,
AVG(Total_Spend) as avg_TS,AVG(Last_Interaction) as avg_LI FROM churn ;
"""
df = pd.read_sql(query,engine)
df

   avg_age  avg_Ten  avg_Fre  avg_SC   avg_PD      avg_TS   avg_LI
0  39.7042  31.3504  15.7148  3.8333  13.4968  620.072766  14.6106

In [31]:
query = """
SELECT 
    Churn,
    AVG(Tenure),
    AVG(Usage_Frequency),
    AVG(Support_Calls),
    AVG(Payment_Delay),
    AVG(Total_Spend),
    AVG(Last_Interaction)
FROM churn
GROUP BY Churn;
"""
df = pd.read_sql(query,engine)
df

,Churn,AVG(Tenure),AVG(Usage_Frequency),AVG(Support_Calls),AVG(Payment_Delay),AVG(Total_Spend),AVG(Last_Interaction)
0,0.0,31.7608,16.2277,2.0258,10.3830,721.394858,13.3877
1,1.0,31.0217,15.3039,5.2814,15.9915,538.899354,15.5903

As, We can see there is not significant difference between churn 0 and 1 for Tenure and Usage Frequency.\
 But there large difference and noticeable increase for churned customer for Support Calls,Payment Delay and Total Spend and little difference for last interaction.\
 That means the stronger association of Support Calls,Payment Delay ,Total Spend and last interaction with the churned customers than Tenure and Usage Frequency.

In [30]:
query = """
 SELECT DISTINCT Churn FROM churn;
"""
df = pd.read_sql(query,engine)
df

  Churn
0   1.0
1   0.0

In [36]:
query = """
SELECT Tenure, COUNT(*)
FROM churn
GROUP BY Tenure;
"""
df = pd.read_sql(query,engine)
print(df.head(10))
print(df.tail(10))

   Tenure  COUNT(*)
0       1      7340
1       2      7512
2       3      7393
3       4      7564
4       5      7636
5       6      8643
6       7      8570
7       8      8582
8       9      8446
9      10      8597
    Tenure  COUNT(*)
50      51      8761
51      52      8964
52      53      8836
53      54      8692
54      55      8984
55      56      8978
56      57      8956
57      58      8775
58      59      8713
59      60      8836

Overall as we can see the customers are more if the Tenure is high which suggests the imbalance.\
So,High Tenure customers may dominate the results.

In [37]:
query = """
SELECT Contract_Length, COUNT(*)
FROM churn
GROUP BY Contract_Length;
"""
df = pd.read_sql(query,engine)
df

  Contract_Length  COUNT(*)
0          Annual    198608
1         Monthly    109234
2       Quarterly    197364

The Annual and Quarterly contract length Customers are nearly equal to ~ 198k .\
Where, Monthly Contract Length Customers are only ~ 110k.\
Again it suggests that Annual and Quarterly Contract length customers may dominate the results due imbalance.

In [38]:
query = """
SELECT Gender, COUNT(*)
FROM churn
GROUP BY Gender;
"""
df = pd.read_sql(query,engine)
df

   Gender  COUNT(*)
0  Female    224933
1    Male    280273

There is slight difference between the number of customers for both difference but Gender may not that much impact on churned customers.

In [39]:
query = """
SELECT Subscription_Type, COUNT(*)
FROM churn
GROUP BY Subscription_Type;
"""
df = pd.read_sql(query,engine)
df

  Subscription_Type  COUNT(*)
0             Basic    164477
1           Premium    170099
2          Standard    170630

As the all three subscriptions type customers are nearly equal which may not impact that much on results